- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install Docker dependencies
      remote_user: root
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      tags:
        - docker
    - name: Add Docker official GPG key
      remote_user: root
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker
    - name: Verify fingerprint
      remote_user: root
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker
    - name: Add Docker Repository
      remote_user: root
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      tags:
        - docker
    - name: Update apt and install docker-ce
      remote_user: root
      apt:
        name: docker-ce
        state: latest
        update_cache: true
      tags:
        - docker
    - name: Install docker-compose
      remote_user: root
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'
      tags:
        - docker